In [1]:
# import libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

from sklearn.preprocessing import MinMaxScaler

In [2]:
# read data

## import datetime
dt = pd.read_csv(r'C:\Users\Marina\Desktop\heat_pump\01.Trekanten\02.outputs\datetime.csv', delimiter=';')
#Time

## import variables
df = pd.read_csv(r'C:\Users\Marina\Desktop\heat_pump\01.Trekanten\02.outputs\trekantenEMA01_ffill.csv', delimiter=';')
df = df.drop(['Unnamed: 0'], axis=1)
df = df.drop(['Time'], axis=1)

df.tail()

temperature_cs1_c1  temperature_cs1_c2  temperature_HS1_c1  \
787616                 9.8                12.3                30.1   
787617                 9.4                11.9                30.1   
787618                 8.9                11.4                30.1   
787619                 8.3                10.7                30.4   
787620                 7.1                 9.6                30.1   

        temperature_HS1_c2  temperature_c1.1  temperature_c1.2  \
787616                37.9              34.1              30.6   
787617                38.0              34.1              30.6   
787618                37.7              34.1              30.6   
787619                38.2              34.4              30.6   
787620                37.9              34.4              30.6   

        temperature_c1.3  temperature_c1.4  temperature_c2.1  \
787616              31.1              17.6             77.50   
787617              31.1              17.6             78.15   
787618              31.1              17.6             77.70   
787619              31.4              17.6             77.70   
787620              31.4              17.6             76.80   

        temperature_c2.2  ...  exp_valve_c2  superheat_c1  superheat_c2  \
787616             39.05  ...          53.0          4.15         10.70   
787617             39.80  ...          54.5          4.60          9.30   
787618             39.45  ...          55.5          5.20          9.20   
787619             40.00  ...          55.0          6.20          8.25   
787620             39.50  ...          55.0          7.50          7.70   

        water_flow_SS1  temperature_TS1_SS1  temperature_TS2_SS1  \
787616            40.0                  0.0                 37.0   
787617            40.0                  0.0                 37.2   
787618            40.0                  0.0                 37.6   
787619            40.0                  0.0                 37.6   
787620            40.0                  0.0                 37.6   

        pressure_t1.c1  pressure_t2.c1  pressure_t1_c2  pressure_t2.c2  
787616            23.3            11.1            10.7             7.7  
787617            24.4            10.8            10.7             7.9  
787618            23.1            10.6            10.7             7.7  
787619            24.2            10.3            10.7             7.9  
787620            23.4             9.9            10.4             7.6  

[5 rows x 29 columns]

In [3]:
variables = ['temperature_cs1_c1', 'temperature_cs1_c2', 'temperature_HS1_c1', 'temperature_HS1_c2','temperature_c1.1', 'temperature_c1.2', 'temperature_c1.3', 'temperature_c1.4', 'temperature_c2.1', 'temperature_c2.2', 'temperature_c2.3', 'temperature_c2.4', 'C1a', 'C1b', 'C2a', 'C2b', 'water_flow_c2', 'water_flow_c1', 'exp_valve_c1', 'exp_valve_c2', 'superheat_c1', 'superheat_c2', 'water_flow_SS1', 'temperature_TS1_SS1', 'temperature_TS2_SS1', 'pressure_t1.c1', 'pressure_t2.c1', 'pressure_t1_c2', 'pressure_t2.c2']
df = pd.concat([dt,df], axis = 1)
df.head()

Time  temperature_cs1_c1  temperature_cs1_c2  \
0  2020-01-01 00:00:00                 4.6                 7.3   
1  2020-01-01 00:01:00                 4.6                 7.3   
2  2020-01-01 00:02:00                 4.6                 7.3   
3  2020-01-01 00:03:00                 4.6                 7.3   
4  2020-01-01 00:04:00                 4.6                 7.3   

   temperature_HS1_c1  temperature_HS1_c2  temperature_c1.1  temperature_c1.2  \
0                37.7                43.1         85.900000             42.30   
1                37.8                43.1         85.922222             42.30   
2                37.7                43.1         86.000000             42.35   
3                37.8                43.1         85.880000             42.34   
4                37.8                43.1         85.950000             42.30   

   temperature_c1.3  temperature_c1.4  temperature_c2.1  ...  exp_valve_c2  \
0         14.411111               7.5         85.277778  ...          31.0   
1         14.555556               7.5         85.188889  ...          31.0   
2         14.512500               7.5         85.125000  ...          31.0   
3         14.510000               7.5         85.200000  ...          30.9   
4         14.425000               7.5         85.287500  ...          31.0   

   superheat_c1  superheat_c2  water_flow_SS1  temperature_TS1_SS1  \
0     12.000000     12.022222           100.0                 14.5   
1     12.055556     11.988889           100.0                 14.6   
2     11.962500     12.000000           100.0                 14.6   
3     11.990000     12.000000           100.0                 14.5   
4     12.075000     12.037500           100.0                 14.5   

   temperature_TS2_SS1  pressure_t1.c1  pressure_t2.c1  pressure_t1_c2  \
0                 32.6            24.9             5.9            24.8   
1                 32.6            24.9             5.9            24.8   
2                 32.7            24.9             5.9            24.8   
3                 32.7            24.9             5.9            24.8   
4                 32.7            24.9             5.9            24.8   

   pressure_t2.c2  
0             5.9  
1             5.9  
2             5.9  
3             5.9  
4             5.9  

[5 rows x 30 columns]

In [4]:
# shorter time period for training - too time expensive

#df = df[variables][:27041]
#dt = dt[:27041]

df = df[variables][:100000]
dt = dt[:100000]

In [5]:
#input
df_input =df[['temperature_cs1_c1', 'temperature_cs1_c2', 'temperature_HS1_c1', 'temperature_HS1_c2', 'water_flow_c2', 'water_flow_c1', 'exp_valve_c1', 'exp_valve_c2']]

# output
df_output = df[['pressure_t2.c1']]

# window_size
df_window = df[['C1a', 'C1b', 'C2a', 'C2b']]

## all inputs and outputs together
dataset = pd.concat([df_input, df_window, df_output], axis = 1)
#dataset = pd.concat([df_input, df_output], axis = 1)
n_features = len(dataset.columns)
print(n_features)
dataset.head()

13


temperature_cs1_c1  temperature_cs1_c2  temperature_HS1_c1  \
0                 4.6                 7.3                37.7   
1                 4.6                 7.3                37.8   
2                 4.6                 7.3                37.7   
3                 4.6                 7.3                37.8   
4                 4.6                 7.3                37.8   

   temperature_HS1_c2  water_flow_c2  water_flow_c1  exp_valve_c1  \
0                43.1           50.0           40.0          32.0   
1                43.1           50.0           40.0          32.0   
2                43.1           50.0           40.0          32.0   
3                43.1           50.0           40.0          32.0   
4                43.1           50.0           40.0          32.0   

   exp_valve_c2  C1a  C1b  C2a  C2b  pressure_t2.c1  
0          31.0  1.0  0.0  0.0  1.0             5.9  
1          31.0  1.0  0.0  0.0  1.0             5.9  
2          31.0  1.0  0.0  0.0  1.0             5.9  
3          30.9  1.0  0.0  0.0  1.0             5.9  
4          31.0  1.0  0.0  0.0  1.0             5.9

In [6]:
# create dataset for model

def create_dataset(dataset, look_back = 1):
    X, Y = [], []
    for i in range(len(dataset) - look_back - 1):
        a = dataset[i:(i+look_back), :]
        X.append(a)
        Y.append(dataset[i + look_back, (n_features - 1)]) # my output variable
    return np.array(X), np.array(Y)

In [7]:
# normalize data

scaler = MinMaxScaler(feature_range=(0,1))
features = scaler.fit_transform(dataset)


print(features)

[[0.52142857 0.875      0.71495327 ... 0.         1.         0.23255814]
 [0.52142857 0.875      0.71962617 ... 0.         1.         0.23255814]
 [0.52142857 0.875      0.71495327 ... 0.         1.         0.23255814]
 ...
 [0.5        0.81944444 0.5        ... 0.         0.         0.41860465]
 [0.5        0.81944444 0.5        ... 0.         0.         0.41860465]
 [0.5        0.81944444 0.5        ... 0.         0.         0.41860465]]


In [8]:
# split the data
feature_size = len(features)
train_size = int(len(features)*0.65)
test_size = len(features) - train_size
train, test = features[0:train_size, :], features[train_size:len(features),:]
print(len(train), len(test))

65000 35000


In [9]:
# reshape into X = t and Y = t+1

look_back = 720 # half a day
X_train, Y_train = create_dataset(train, look_back)
X_test, Y_test = create_dataset(test, look_back)

In [10]:
# reshape input to be [samples, time steps, features]
X_train = np.reshape(X_train, (X_train.shape[0], look_back, n_features))
X_test = np.reshape(X_test, (X_test.shape[0], look_back, n_features))

In [11]:
# MODEL 03

model = tf.keras.models.Sequential([
    tf.keras.layers.LSTM(128, input_dim = n_features, return_sequences = True), 
    tf.keras.layers.LSTM(64),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(1)
])

model.compile(optimizer = tf.keras.optimizers.Adam(), # learning rate standard = 0.0001
    loss = tf.keras.losses.MeanSquaredError(),
    metrics = ['accuracy']
)

model.summary()

# checkpoint - to be removed when too memory expensive to store all 'best' models
#checkpoint = tf.keras.callbacks.ModelCheckpoint('model_LSTM-{epoch:02d}-{val_loss:.3f}.hdf5', monitor = 'val_loss', verbose = 1, save_best_only = True, mode = 'min')
earlystop = tf.keras.callbacks.EarlyStopping(monitor = 'val_loss', patience = 5, min_delta = 0)
reduce = tf.keras.callbacks.ReduceLROnPlateau(monitor = 'val_loss', patience = 5, min_delta = 0)


history = model.fit(X_train,
                    Y_train,
                    epochs = 100,
                    validation_data = (X_test,Y_test),
                    callbacks = [reduce]
#                    callbacks = [earlystop, checkpoint]
)

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm (LSTM)                  (None, None, 128)         72704     
_________________________________________________________________
lstm_1 (LSTM)                (None, 64)                49408     
_________________________________________________________________
dropout (Dropout)            (None, 64)                0         
_________________________________________________________________
dense (Dense)                (None, 1)                 65        
Total params: 122,177
Trainable params: 122,177
Non-trainable params: 0
_________________________________________________________________
Epoch 1/100
2009/2009 [==============================] - 1626s 808ms/step - loss: 0.0049 - accuracy: 5.6006e-04 - val_loss: 0.0060 - val_accuracy: 0.0000e+00
Epoch 2/100
2009/2009 [==============================] - 1597s 795ms/step - loss: 0.0017 -

KeyboardInterrupt: 

In [ ]:
# visualize the losses 

def visualize_loss(history, title):
    loss = history.history['loss']
    val_loss = history.history['val_loss']
    epochs = range(len(loss))
    plt.figure()
    plt.plot(epochs, loss, 'b', label='train loss')
    plt.plot(epochs, val_loss, 'r', label='val loss')
    plt.title(title)
    plt.xlabel('epoch')
    plt.ylabel('loss')
    plt.legend()
    plt.show()
    print('final val loss: ', val_loss)

visualize_loss(history, 'training and validation loss')

In [ ]:
# make predictions

trainPrediction = model.predict(X_train)
print(trainPrediction)

testPrediction = model.predict(X_test)
print(testPrediction)

In [ ]:
# need to transform the predictions back from normalization

# get something which has as many features as dataset
trainPrediction_extended = np.zeros((len(trainPrediction), n_features))
# Put the predictions there
trainPrediction_extended[:,(n_features - 1)] = trainPrediction[:,0]
# inverse transform it and select the last column
trainPrediction = scaler.inverse_transform(trainPrediction_extended)[:,(n_features - 1)]
print(trainPrediction)

# get something which has as many features as dataset
testPrediction_extended = np.zeros((len(testPrediction), n_features))
# Put the predictions there
testPrediction_extended[:,(n_features - 1)] = testPrediction[:,0]
# inverse transform it and select the last column
testPrediction = scaler.inverse_transform(testPrediction_extended)[:,(n_features - 1)]
print(testPrediction)

In [ ]:
Y_train_exteded =np.zeros((len(Y_train), n_features))
Y_train_exteded[:,(n_features - 1)] = Y_train
Y_train = scaler.inverse_transform(Y_train_exteded)[:,(n_features - 1)]

Y_test_exteded =np.zeros((len(Y_test), n_features))
Y_test_exteded[:,(n_features - 1)] = Y_test
Y_test = scaler.inverse_transform(Y_test_exteded)[:,(n_features - 1)]

In [ ]:
# shift train predictions for plotting
trainPredictionPlot = np.empty_like(features)
trainPredictionPlot[:, :] = np.nan
trainPredictionPlot[look_back:len(trainPrediction)+look_back, (n_features - 1)] = trainPrediction

# shift test predictions for plotting
testPredictionPlot = np.empty_like(features)
testPredictionPlot[:, :] = np.nan
testPredictionPlot[len(trainPrediction)+(look_back*2) +1:len(features)-1, (n_features - 1)] = testPrediction

In [ ]:
# plot original

plt.figure(figsize=(10,6))
plt.plot(scaler.inverse_transform(features)[:,(n_features - 1)])
#plt.plot(scaler.inverse_transform(features[train_size:])[:,8], linestyle = '-')  
plt.plot(trainPredictionPlot, 'r', linestyle='--', alpha = 0.4)  
plt.plot(testPredictionPlot, 'pink', linestyle='--', alpha = 0.6)
plt.title('pressure t2.c1')
plt.ylabel('bar')
plt.xlabel('time step')
plt.legend(['observation','simulation'], loc='upper right')

In [ ]:
# plot zoom validation
zoom = 18000
end = 27000

plt.figure(figsize=(10,6))
plt.plot(scaler.inverse_transform(features)[:,(n_features - 1)][zoom:end])
#plt.plot(scaler.inverse_transform(features[train_size:])[:,8], linestyle = '-')  
plt.plot(trainPredictionPlot[zoom:end], 'r', linestyle='--', alpha = 0.4)  
plt.plot(testPredictionPlot[zoom:end], 'pink', linestyle='--', alpha = 0.7)
plt.title('pressure t2.c1')
plt.ylabel('bar')
plt.xlabel('time step')
plt.legend(['observation','simulation'], loc='upper right')